---

task-docker-image: &task-docker-image "task-docker-image"

# -------------------------------
resources:
# -------------------------------
- name: iso
  type: git
  source:
    uri: git@github.com:corgiponcho/iso.git
    branch: master
    private_key: ((corgi-poncho-bot-private-key))

- name: iso-ci
  type: git
  source:
    uri: git@github.com:corgiponcho/iso-ci.git
    branch: master
    private_key: ((corgi-poncho-bot-private-key))

- name: task-docker-image
  type: docker-image
  source:
    repository: corgiponcho/iso
    tag: "1.0.1"
    username: ((docker_hub_username))
    password: ((docker_hub_password))

# -------------------------------
jobs:
# -------------------------------
- name: run-jest-tests
  plan:
  - get: iso
    trigger: true
  - get: iso-ci
  - get: task-docker-image
  - task: run-jest-tests
    file: iso-ci/tasks/run-jest-test.yml
    image: *task-docker-image

- name: run-mocha-tests
  plan:
  - get: iso
    trigger: true
  - get: iso-ci
  - get: task-docker-image
  - task: run-mocha-tests
    file: iso-ci/tasks/run-mocha-test.yml
    image: *task-docker-image
    params:
      NODE_ENV: test
