#!/usr/bin/env bash

set -xeu

export ROOT_DIR=$(pwd)

cd ${ROOT_DIR}/iso

npm install

/etc/init.d/postgresql start

psql -U postgres -c "CREATE DATABASE iso_dev"

node server/index.js

npm run test:mocha