#!/usr/bin/env bash

set -xeu

export ROOT_DIR=$(pwd)

cd ${ROOT_DIR}/iso

/etc/init.d/postgresql start

psql -U postgres -c "CREATE DATABASE iso_test"

node server/index.js

npm install
npm run test:mocha